# Generated by Django 5.1.6 on 2025-02-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizhistory_userresponse_quiz_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='batch_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
