# Generated by Django 3.1 on 2025-02-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizhistory',
            name='mode',
            field=models.CharField(choices=[('random', 'Random'), ('sequential', 'Sequential')], default='random', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizhistory',
            name='progress_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizhistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
